version: '3.7'
services:
  iris:
    build:
      context: ./iris
    volumes:
      - ./iris:/tmp/iris
    # command: -a "sh server_start.sh"
    ports:
    - 52775:52773
    - 51776:1972
    - 4040:8080
    - 4041:8081
  angular:
    build:
      context: ./angular
    ports:
      - 8080:80