version: '3.7'
services:
  iris:
    build:
      context: ./iris
    volumes:
      - ./iris:/tmp/iris
    ports:
    - 52775:52773
    - 51776:1972
  angular:
    build:
      context: ./angular
    ports:
      - 8080:80